services:
  db:
    container_name: pile-db
    image: postgres:alpine
    environment:
      POSTGRES_DB: pile
      POSTGRES_USER: cicd
      POSTGRES_PASSWORD: pipeline
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cicd -d pile"]
      interval: 5s
      timeout: 5s
      retries: 5
  migrations:
    build: 
      dockerfile: ./migrations.Dockerfile
    depends_on:
      db:
        condition: service_healthy
  api:
    build: 
      dockerfile: ./api.Dockerfile
    depends_on:
      db:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully
    ports:
      - 3000:3000
