name: Pile Challenge Backend API
on: [ push ]
jobs:
  lint-test-build:
    runs-on: ubuntu-latest
    env:
      DB_HOSTNAME: pile-db
      DB_USERNAME: cicd
      DB_PASSWORD: pipeline
      DB_DATABASE: pile
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - run: npm install
      - run: npm run lint
      - run: npm test
      - run: npm run build
    services:
      pile-db:
        image: postgres:alpine
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: pile
          POSTGRES_USER: cicd
          POSTGRES_PASSWORD: pipeline
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
