name: Pile Challenge Backend API
on: [ push ]
jobs:
  lint-test-build:
    runs-on: ubuntu-latest
    env:
      DB_HOSTNAME: pile-db
      DB_USERNAME: cicd
      DB_PASSWORD: pipeline
      DB_DATABASE: pile
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - run: npm install
      - run: npm run lint
      - run: npm run test:local
      - run: npm run build
  deploy:
    runs-on: ubuntu-latest
    needs: lint-test-build
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - run: npm install
      - run: npm run build
      - run: npm run deploy --if-present
